### ISSUE TITLE
`change-freq` is not documented

### ISSUE THREAD

**Issue by vassbence** [bartholomej/svelte-sitemap#19]
Hi!

First eval thanks for the wonderful package!

Just noticed a small thing: `change-freq` is implemented but not documented in the README.

**Comment by bartholomej** [comment]
Hi Vass,
nice find! :) 

The main reason it is not documented is that it is applied to all pages in the sitemap.xml. Now there is no way to select this parameter for individual pages, because the generator works dynamically. 
This kind of setup is usually not what we would want to use and can look confusing in the documentation...

Are you using this parameter? 
Do you have an example or idea where it could be used for all pages like this?

**Comment by vassbence** [comment]
I was rewriting a small app (which used Next.js and next-sitemap) into sveltekit and wanted to match the existing sitemap exactly. This is why I looked this parameter up and am currently using it for the previously mentioned reason.

In next-sitemap this option is global and defaults for "daily" for every page with no API to change it on a per page basis. Not sure if this is a good idea or that it would be a good default for svelte-sitemap too.

**Comment by bartholomej** [comment]
OK, that makes sense. I've made a slightly more robust implementation and added a mention about `changeFreq` [in the readme](https://github.com/bartholomej/svelte-sitemap#options). The default state is empty.

Let me know how it works in new version `v2.2.0` ;)
